/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ticketcine.Vista;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import ticketcine.Controlador.Cliente;
import ticketcine.Controlador.DetallesCine;
import ticketcine.Controlador.DetallesCompra;
import ticketcine.Controlador.DetallesPase;

/**
 *
 * @author arant
 */
public class ConsultarCompras extends javax.swing.JFrame {

    private JFrame vAnterior; 
    private Cliente cliente;
    DefaultListModel modeloLista;
   
    /**
     * Creates new form Cartelera
     */
    public ConsultarCompras(Cliente cliente, JFrame Vanterior) {
        initComponents();
        this.cliente = cliente;
        this.vAnterior = Vanterior;
        
        modeloLista = new DefaultListModel();
        listCompras.setModel(modeloLista);
        ArrayList compras = this.cliente.consultarCompras();
        
        for(Object item:compras)
        {
            modeloLista.addElement(item);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelCompras = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listCompras = new javax.swing.JList<>();
        botonAtras = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        textAreaCritica = new javax.swing.JTextArea();
        botonRealizarCritica = new javax.swing.JButton();
        labelNombrePelicula = new javax.swing.JLabel();
        labelFechaCompra = new javax.swing.JLabel();
        labelSalaHora = new javax.swing.JLabel();
        labelNumEntradas = new javax.swing.JLabel();
        labelNombreCine = new javax.swing.JLabel();
        labelDireccionCine = new javax.swing.JLabel();
        labelPoblacionCine = new javax.swing.JLabel();
        labelTlfCine = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consultar Compras");

        labelCompras.setText("Compras");

        listCompras.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listCompras.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listComprasValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listCompras);

        botonAtras.setText("ATRÁS");
        botonAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonAtrasActionPerformed(evt);
            }
        });

        textAreaCritica.setColumns(20);
        textAreaCritica.setRows(5);
        jScrollPane2.setViewportView(textAreaCritica);

        botonRealizarCritica.setText("REALIZAR CRÍTICA");
        botonRealizarCritica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonRealizarCriticaActionPerformed(evt);
            }
        });

        labelNombrePelicula.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCompras))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNumEntradas)
                            .addComponent(labelNombrePelicula))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(botonRealizarCritica)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelSalaHora)
                            .addComponent(labelFechaCompra))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelDireccionCine)
                            .addComponent(labelNombreCine)
                            .addComponent(labelPoblacionCine)
                            .addComponent(labelTlfCine))
                        .addGap(56, 56, 56))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(botonAtras)
                .addGap(43, 43, 43))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(labelCompras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(94, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombrePelicula)
                                .addGap(45, 45, 45)
                                .addComponent(labelFechaCompra)
                                .addGap(26, 26, 26)
                                .addComponent(labelSalaHora)
                                .addGap(28, 28, 28)
                                .addComponent(labelNumEntradas))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(labelNombreCine)
                                .addGap(18, 18, 18)
                                .addComponent(labelDireccionCine)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelPoblacionCine, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelTlfCine)))
                        .addGap(38, 38, 38)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(botonRealizarCritica)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonAtras)
                        .addGap(33, 33, 33))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAtrasActionPerformed
        this.vAnterior.setVisible(true);
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_botonAtrasActionPerformed

    private void botonRealizarCriticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRealizarCriticaActionPerformed
        
        String comentario = textAreaCritica.getText();
        
        int index= listCompras.getSelectedIndex();

        if(index >= 0)
        {
            cliente.realizarCritica(index, comentario);
            JOptionPane.showMessageDialog(this, "Crítica realizada con éxito");
            textAreaCritica.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Selecciona una compra antes de realizar una crítica");
        }
       
    }//GEN-LAST:event_botonRealizarCriticaActionPerformed

    private void listComprasValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listComprasValueChanged
        
        Object compra_aux = listCompras.getSelectedValue();
        
        DetallesPase dc = this.cliente.consultarDetallesCompraPase(compra_aux);
        DetallesCompra dco = this.cliente.consultarDetallesCompra(compra_aux);
        DetallesCine dci = this.cliente.consultarDetallesCompraCine(compra_aux);
        
        labelNombrePelicula.setText(dc.pelicula.toString());
        labelFechaCompra.setText(dc.fecha.toString());
        labelSalaHora.setText("Sala " + dc.sala.toString() + " a las " + dc.hora.toString() + " h");
        labelNumEntradas.setText("Nº de entradas: " + dco.n_entradas);
        labelNombreCine.setText(dc.cine.toString());
        labelDireccionCine.setText(dci.direccion);
        labelPoblacionCine.setText(dci.cp + " " + dci.poblacion);
        labelTlfCine.setText("Tlf: " + dci.tlf);
    }//GEN-LAST:event_listComprasValueChanged



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonAtras;
    private javax.swing.JButton botonRealizarCritica;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelCompras;
    private javax.swing.JLabel labelDireccionCine;
    private javax.swing.JLabel labelFechaCompra;
    private javax.swing.JLabel labelNombreCine;
    private javax.swing.JLabel labelNombrePelicula;
    private javax.swing.JLabel labelNumEntradas;
    private javax.swing.JLabel labelPoblacionCine;
    private javax.swing.JLabel labelSalaHora;
    private javax.swing.JLabel labelTlfCine;
    private javax.swing.JList<Object> listCompras;
    private javax.swing.JTextArea textAreaCritica;
    // End of variables declaration//GEN-END:variables
}
